---
title: "Seguimiento de commits"
output: html_notebook
---

configuracion de directorios

```{r}


getwd()

```

Configuracion de Git para que los comandos magicos funcionen


```{r}
system("git config --global user.email \"ronald.bailey@galileo.edu\"")
system("git config --global user.name \"ronaldbailey\"")

```



```{r}

system("git add .")
system("git commit -m \"Reparacion de formatos\" ")
system("git push")
```

```{r}

system("git add .")
system("git commit -m \"Prueba de graficas\" ")
system("git push")
```

```{r}

system("git add .")
system("git commit -m \"Creacion de archivos a utilizar\" ")
system("git push")
```


```{r}

system("git add .")
system("git commit -m \"Primera y segunda pregunta\" ")
system("git push")
```





```{r}

system("git add .")
system("git commit -m \"Tercera preguta\" ")
system("git push")
```





```{r}

system("git add .")
system("git commit -m \"cuarta preguta\" ")
system("git push")
```







```{r}

system("git add .")
system("git commit -m \"sexta preguta\" ")
system("git push")
```

```{r}

system("git add .")
system("git commit -m \"primera parte\" ")
system("git push")
```
```{r}

system("git add .")
system("git commit -m \"primera parte redme\" ")
system("git push")
```




```{r}

system("git add .")
system("git commit -m \"Segunda parte redme\" ")
system("git push")
```


```{r}

system("git add .")
system("git commit -m \"Segunda parte redme\" ")
system("git push")
```

```{r}

system("git add .")
system("git commit -m \"Segunda parte 1\" ")
system("git push")
```










